### PR TITLE
Add CI link validation

### PR DESCRIPTION
**Pull request by cldwalker**
Following up on #71, I've added a CI process to validate internal and external links in markdown files.

@Mitzi-Laszlo I fixed a couple more links. Once this lands this CI process will run on every pull request. If a link is private or if a server doesn't consistently respond with a successful response, we would need to add an ignore for that url. For example if the url `example.com` was a private link you would extend the -i statement on line 6 of .travis.yml to read `-i 'linkedin.com/in/|vimeo.com/|gitter.im/solid/team|example.com'`. Feel free to ping me if you need help with any of the .travis.yml configuration

@kjetilk @Mitzi-Laszlo  I've made a basic travis config file. You can see an example of a [failing build](https://travis-ci.org/cldwalker/community/builds/506399446) and then a [passing one](https://travis-ci.org/cldwalker/community/builds/506486417) after I fixed some invalid links. I ended up using two libraries to accomplish link validation: [markdown-link-validator](https://github.com/webhintio/markdown-link-validator/) and remark [with a plugin](https://github.com/remarkjs/remark-validate-links). The first library does the best job of npm libraries I saw of finding the most markdown links, printing an actionable report and allowing for configured links to be ignored. The second library does a good job of detecting different internal links including headers and relative files.Let me know if there's any standard solid config you'd like to add e.g. notification emails or feel free to tweak the config as well.

### CODE REVIEW

**Comment by Mitzi-Laszlo** [comment]
Great! Thanks @cldwalker

**Comment by cldwalker** [comment]
Happy to help :) Would recommend merging soon so it can validate PRs with a number of new links like #74

**Comment by Mitzi-Laszlo** [comment]
@cldwalker thank you wonderful, any chance you could resolve the conflicts?

**Comment by cldwalker** [comment]
@Mitzi-Laszlo Ready to go with [CI passing again](https://travis-ci.org/cldwalker/community/jobs/512617480)

**Comment by cldwalker** [comment]
@kjetilk Could you enable the [repo in travis](https://travis-ci.org/solid/information)?

**Comment by cldwalker** [comment]
@kjetilk Thanks!

**Pull request merged**
