### PR TITLE
Update license.md

### PR DESCRIPTION
**Pull request by TallTed**
* `- present` is not valid for copyright statements
* `firstyear–latestyear` construct is a valid construct

### CODE REVIEW

**Comment by Mitzi-Laszlo** [comment]
Do you have a legal reference about the correct way to date an MIT license? Does that mean that every year one has to update all the licences?

**Comment by TallTed** [comment]
Note that my PR does not "date an MIT license." It corrects the *copyright statement* which is part of the license document.

[Numerous references available on the web](https://www.google.com/search?q=copyright+statement+format), including government publications (which tend to be somewhat nationally focused, but are generally for signatories of recent copyright conventions) showing the correct form of copyright statements.

**Comment by Mitzi-Laszlo** [comment]
Thank you for the link @TallTed 

Noticing that these are examples of who it's done otherwise. Wondering if you have any reference saying that "2017 - present" would invalidate the license?

**Comment by TallTed** [comment]
@Mitzi-Laszlo - I do not believe including "- present" would invalidate the "copyright notice" (which, again, is distinct from the license); "- present" is basically meaningless in a copyright notice/statement. "- present" does not have the effect of enumerating any year (unless, possibly, the document on which it is placed is itself dated, so including some definition of "present", but this would be determined by the judge, magistrate, etc., during litigation on each and every copyright infringement lawsuit), so it's pointless to include it, even if it leaves the rest of the notice in play; and it's arguably problematic as it may lead people who should be adding a year to the enumerated list to *not* do so, which would let that declared copyright expire sooner than it otherwise would.

**Comment by TallTed** [comment]
Conflicts resolved... Again ready to merge.

**Comment by Mitzi-Laszlo** [comment]
Let's get the view of a professional and adapt all the licenses accordingly so that all repos have a uniform approach.

**Pull request closed without merging**
